### ISSUE TITLE
Make it easier to register dataloaders from PHP (autowire autoconfigure)

### ISSUE THREAD

**Issue by ruudk** [overblog/dataloader-bundle#21]
Currently, it seems only possible to create data loaders dynamically with the bundle's configuration.

But that registers dynamic services that you need to inject in your resolvers.

If you use autowire, that becomes a pain. 

What if you can just create a dataloader with PHP, and that this bundle automatically finds it and registers it?

**Comment by mcg-web** [comment]
I totally agree with this, just not yet have the time to work on this. We should maybe just make loader tagged services so we can easily use DI autoconfigure to load an tag them, what do you think of this solution?

**Comment by ruudk** [comment]
I used this https://github.com/overblog/dataloader-bundle/pull/20 as an example and it works, so we can close this :)
