### ISSUE TITLE
Introspection fails with "Found no active DataLoader instance."

### ISSUE THREAD

**Issue by AndreasHeiberg** [overblog/dataloader-bundle#5]
Using a setup like this https://github.com/overblog/GraphQLBundle/pull/73#issuecomment-285598005

I get "Found no active DataLoader instance." when running any introspection query.

Sorry that I can't provide you more detail. Does this ring any bells though?

**Comment by mcg-web** [comment]
Hi @AndreasHeiberg,
Can you give me the version of dataloader-php you use please?

**Comment by AndreasHeiberg** [comment]
the latest one; 0.5.1

**Comment by mcg-web** [comment]
Can you try to add an `else { return $promise; }` bloc [here](https://github.com/overblog/dataloader-php/blob/master/src/DataLoader.php#L276) to see if it fix the issue?

**Comment by AndreasHeiberg** [comment]
Major :man_facepalming: I just now realise that your latest version of the dataloader-bundle requires a very old version of dataloader-php so I was on that version not on 0.5.1 as expected. All is resolved.
