### ISSUE TITLE
DataLoader destroyed before promise complete.

### ISSUE THREAD

**Issue by andheiberg** [overblog/dataloader-bundle#9]
I've managed to hit `DataLoader destroyed before promise complete.` in [this file](https://github.com/overblog/dataloader-php/blob/master/src/DataLoader.php#L87).

Since I'm using the bundle it's not explicitly clear how I got to a broken state.

It's likewise hard to create a minimal test case.

Any clues why this might happen?

**Comment by mcg-web** [comment]
Hi, can you give me the vendors (graphql-php, dataloader-php, graphql-bundle)  versions please?

**Comment by andheiberg** [comment]
```
webonyx/graphql-php                         v0.9.11
overblog/dataloader-bundle                  v0.3.0
overblog/dataloader-php                     v0.5.1
```

**Comment by mcg-web** [comment]
thanks, are you also using native graphql promise adapter?

**Comment by andheiberg** [comment]
Yes

**Comment by mcg-web** [comment]
Ok thanks, can you try to update to webonyx/graphql-php v0.9.14 and overblog/dataloader-php v0.5.2, we fix recently some bugs on the SyncAdapter, that could be the solution...

**Comment by andheiberg** [comment]
Yup that fixed it 👍
